# This example was generated by AI and is provided for demonstration purposes only.
#
# Example of connecting to OpenAI directly instead of going through SAP's
# Generative AI Hub (see gen_ai_llm_call.py). Mirrors the generate_gpt /
# generate_gpt_with_timeout call shape used by the rest of round_trip so it
# is a drop-in replacement for GPT_STYLE_CALLS['gpt'] in generation_pipeline.py.
#
# Requires an OPENAI_API_KEY entry in the project-root .env file.

import os
import signal

import dotenv
from openai import OpenAI

current_dir = os.path.dirname(__file__)
project_root = os.path.abspath(os.path.join(current_dir, os.pardir, os.pardir))
dotenv_path = os.path.join(project_root, '.env')
dotenv.load_dotenv(dotenv_path=dotenv_path)

client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

GPT_MODEL_NAME = "gpt-5"
MAX_OUTPUT_TOKENS = 8000
CALL_TIMEOUT_SECONDS = 120
MAX_RETRIES = 1


def timeout_handler(signum, frame):
    raise TimeoutError()


def _call_with_timeout(func, args, label):
    """Call func(*args), aborting via SIGALRM after CALL_TIMEOUT_SECONDS, retrying up to MAX_RETRIES times on timeout."""
    retry_count = 0

    while retry_count < MAX_RETRIES:
        signal.signal(signal.SIGALRM, timeout_handler)
        signal.alarm(CALL_TIMEOUT_SECONDS)
        try:
            return func(*args)
        except TimeoutError:
            print(f"{label} call timed out. Retrying...")
            retry_count += 1
        except Exception as ex:
            print(f"An unexpected error occurred in {label}: {ex}. Proceeding to next iteration.")
            return None
        finally:
            signal.alarm(0)  # disable alarm whether we succeeded, timed out, or errored

    print("Max retries exceeded. Proceeding to next iteration.")
    return None


def generate_gpt(system_prompt, user_prompt, assistant_prompt, prompt, temperature, response_format=True):
    """Same call shape as gen_ai_llm_call.generate_gpt, but talks to the OpenAI API directly."""
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
        {"role": "assistant", "content": assistant_prompt},
        {"role": "user", "content": prompt},
    ]

    kwargs = dict(
        model=GPT_MODEL_NAME,
        messages=messages,
        temperature=temperature,
        max_completion_tokens=MAX_OUTPUT_TOKENS,
    )
    if response_format:
        kwargs["response_format"] = {"type": "json_object"}

    response = client.chat.completions.create(**kwargs)
    return response.choices[0].message.content


def generate_gpt_with_timeout(system_prompt, user_prompt, assistant_prompt, prompt, temperature, response_format=True):
    return _call_with_timeout(
        generate_gpt, (system_prompt, user_prompt, assistant_prompt, prompt, temperature, response_format), "generate_gpt"
    )


if __name__ == "__main__":
    system_prompt = (
        "You are a BPMN2.0 expert who can convert textual information to a BPMN model in JSON and vice versa. "
        "Given an input BPMN model in JSON format with the usual elements (tasks, events, gateways, pools "
        "containing lanes, sequence flows, and possibly message flows) describe the process from beginning to "
        "end accurately in the order that it happens."
    )
    user_prompt = (
        'input: {"tasks": [{"id": "t1", "name": "Review application", "type": "User"}], '
        '"events": [{"id": "e1", "name": "start", "type": "StartNoneEvent"}, '
        '{"id": "e2", "name": "end", "type": "EndNoneEvent"}], '
        '"gateways": [], "pools": [], "sequenceFlows": [], "messageFlows": []}'
    )
    assistant_prompt = "output: The process starts, an employee reviews the application, then the process ends."
    prompt = "Here is the textual description: A customer submits a loan application, which a bank employee then reviews before approving or rejecting it."

    result = generate_gpt_with_timeout(
        system_prompt, user_prompt, assistant_prompt, prompt, temperature=0, response_format=False
    )
    print(result)
